"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var parcel_controller_1 = require("../controllers/parcel.controller");
var business_controller_1 = require("../controllers/business.controller");
var router = (0, express_1.Router)();
router.get("/parcels", parcel_controller_1.GetClientParcels);
router.post("/parcels/cancellation", parcel_controller_1.CancelParcel);
router.get("/parcels/:id", parcel_controller_1.GetClientParcel);
router.get("/pickups", business_controller_1.GetPickupsForClient);
exports.default = router;
