"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var parcel_controller_1 = require("../controllers/parcel.controller");
var router = (0, express_1.Router)();
router.post("/", parcel_controller_1.registerParcel);
router.get("/", parcel_controller_1.GetParcels);
router.post("/dispatch/bulk", parcel_controller_1.dispatchParcels);
router.get("/grouped", parcel_controller_1.getParcels);
router.put("/:id/arrive", parcel_controller_1.markParcelArrived);
router.put("/:id/collect", parcel_controller_1.collectParcel);
router.get("/:id/journey", parcel_controller_1.GetParcelJourney);
router.get("/trucks/count", parcel_controller_1.getTruckParcelCount);
router.get("/status/count", parcel_controller_1.getParcelStatusCount);
router.get("/events/stats", parcel_controller_1.getFullDashboard);
exports.default = router;
